name: Setup and Build Executable
description: 'Reusable action for building PALMS executables'
inputs:
  os:
    description: 'os'
    required: true
  artifact-name:
    description: 'Name for uploaded artifact'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.6'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable
      shell: bash
      run: |
        EXCLUDED_MODULE_OPTIONS=" \
          --exclude-module PyQt5  \
          --exclude-module PyQt6.Qt6.translations  \
          --exclude-module PyQt6.Qt6.lib.libQt6Pdf  \
          --exclude-module PyQt6.Qt6.lib.libicudata  \
          --exclude-module PyQt6.Qt6.Qt6Network \
          --collect-data PyQt6.Qt6.plugins
        "
        COMMON_OPTIONS="--windowed --noconfirm --clean"

        if [[ "${{ inputs.os }}" == "macos-latest" ]]
        then
          pyinstaller ${EXCLUDED_MODULE_OPTIONS} ${COMMON_OPTIONS} --add-data "resources:resources" --onedir --icon resources/palms.icns PALMS.py
          mkdir -p release
          tar -czf release_macos.tar.gz Experiments -C dist ./
          mv release_macos.tar.gz release/
        elif [[ "${{ inputs.os }}" == "windows-latest" ]]
        then
          pyinstaller ${EXCLUDED_MODULE_OPTIONS} ${COMMON_OPTIONS} --add-data "resources;resources" --onefile --icon resources/palms.ico PALMS.py
          mkdir -p release
          cd dist
          7z a -tzip ../release_windows.zip PALMS.exe
          cd ..
          7z a -tzip release_windows.zip Experiments
          mv release_windows.zip release/
        else
          pyinstaller ${EXCLUDED_MODULE_OPTIONS} ${COMMON_OPTIONS} --add-data "resources:resources" --onefile --icon resources/palms.png PALMS.py
          mkdir -p release
          chmod +x dist/PALMS
          tar -czf release_linux.tar.gz Experiments -C dist PALMS
          mv release_linux.tar.gz release/
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: release/
