name: Build Executables

on:
  push:
    branches: [release]

jobs:
  build:
    name: Build executables
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linux
          - os: windows-latest
            target: windows
          - os: macos-latest
            target: macos

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: '3.12.6'
        cache: 'pip'

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          pip-${{ runner.os }}-

    - name: Install Python deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller pyside6

    # ---- MacOS build ----
    - name: Build Mac app bundle
      if: matrix.target == 'macos'
      run: |
        pyinstaller PALMS.py \
          --noconfirm \
          --onedir \
          --windowed \
          --icon=resources/palms.icns \
          --add-data "resources:resources" \
          --strip

    - name: Self-sign Mac app bundle (ad-hoc)
      if: matrix.target == 'macos'
      run: |
        find dist/PALMS.app -type f -exec codesign --force --sign - {} \;
        codesign --force --options runtime --deep --sign - dist/PALMS.app

    - name: Make Mac app executable
      if: matrix.target == 'macos'
      run: chmod +x dist/PALMS.app/Contents/MacOS/PALMS

    - name: Archive macOS app
      if: matrix.target == 'macos'
      run: |
        tar --no-xattrs -czf release/palms-macos.tar.gz Experiments -C dist PALMS.app

    # ---- Linux build ----
    - name: Build Linux executable
      if: matrix.target == 'linux'
      run: |
        pyinstaller PALMS.py \
          --noconfirm \
          --onefile \
          --windowed \
          --icon=resources/palms.png \
          --add-data "resources:resources" \
          --strip

    - name: Make Linux binary executable
      if: matrix.target == 'linux'
      run: chmod +x dist/PALMS

    - name: Archive Linux binary
      if: matrix.target == 'linux'
      run: |
        tar -czf release/palms-linux.tar.gz Experiments -C dist PALMS

    # ---- Windows build ----
    - name: Build Windows executable
      if: matrix.target == 'windows'
      run: |
        pyinstaller PALMS.py ^
          --noconfirm ^
          --onefile ^
          --windowed ^
          --icon=resources/palms.ico ^
          --add-data "resources;resources" ^
          --strip

    - name: Archive Windows binary
      if: matrix.target == 'windows'
      run: |
        7z a -tzip release/palms-windows.zip dist/PALMS.exe
        7z a -tzip release/palms-windows.zip Experiments

    # ---- Common steps ----
    - name: Commit latest tag
      if: github.ref == 'refs/heads/release'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag -f latest
        git push origin latest --force

    - uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: latest
        files: release/*

    - if: failure()
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: latest
        files: release/*
