name: Build and Test MacOS Executable

on:
  push:
    branches:
      - release
      - release-test

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-and-build
        with:
          os: macos-latest
          artifact-name: macos-latest-release

  test-macos:
    name: Test macOS Executable
    runs-on: macos-latest
    needs: build-macos
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-latest-release
          path: release/

      - name: Extract .tar.gz
        shell: bash
        run: |
          mkdir -p dist
          tar -xzf release/release_macos.tar.gz -C dist

      - name: Make app executable
        shell: bash
        run: chmod +x dist/PALMS.app/Contents/MacOS/PALMS

      - name: Run app, screenshot, and check for errors
        shell: bash
        run: |
          set -euo pipefail
          {
            echo "Start time: $(date '+%Y-%m-%d %H:%M:%S.%3N')"
            dist/PALMS.app/Contents/MacOS/PALMS --smoke-test Experiments/Haselgrove_etal_2010_exp1.rw &
            PID=$!
            sleep 30
            echo "Making screenshot"
            screencapture -x screenshot-macos.png
            wait $PID
            EXIT_CODE=$?
            echo "End time: $(date '+%Y-%m-%d %H:%M:%S.%3N')"
            echo "App exited with code $EXIT_CODE"
            if [ $EXIT_CODE -ne 0 ]; then
              exit 1
            fi
          } 2>&1 | tee run.log

      - name: Upload screenshot artifact (will download as screenshot-macos.zip)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshot-macos
          path: screenshot-macos.png

      - name: Add screenshot and logs to Job Summary
        if: always()
        shell: bash
        run: |
          {
            echo "## macOS Smoke Test"
            echo
            if [[ -f screenshot-macos.png ]]; then
              echo "### Screenshot"
              echo "![screenshot](screenshot-macos.png)"
              echo
            else
              echo "> (No screenshot produced)"
            fi
            echo "### Logs"
            echo '```text'
            if [[ -f run.log ]]; then cat run.log; fi
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Create or update "latest" tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -f latest
          git push origin latest --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact to Releases
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: release/release_macos.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

