name: Build Linux Executable

on:
  push:
    branches: [release]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-and-build
        with:
          os: ubuntu-latest
          artifact-name: linux-latest-release
